imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

liip_functional_test: ~

doctrine:
    dbal:
        host:     127.0.0.1
        dbname:   bugtracker_test
        user:     root
        password: 123

