services:
    app.twig_extension:
        class: Oro\BugTrackerBundle\Twig\PaginatorExtension
        public: false
        tags:
            - { name: twig.extension }

    oro_bugtracker.handler.project:
        class: Oro\BugTrackerBundle\Form\Handler\ProjectHandler
        public: true
        arguments:
            ["@request_stack","@doctrine.orm.entity_manager"]

    oro_bugtracker.handler.issue:
            class: Oro\BugTrackerBundle\Form\Handler\IssueHandler
            public: true
            arguments:
                ["@request_stack","@doctrine.orm.entity_manager","@security.token_storage"]

    oro_bugtracker.handler.customer:
            class: Oro\BugTrackerBundle\Form\Handler\CustomerHandler
            public: true
            arguments:
                ["@request_stack","@doctrine.orm.entity_manager","@security.password_encoder"]