services:
    oro_bugtracker.twig_extension.paginator:
        class: Oro\BugTrackerBundle\Twig\PaginatorExtension
        public: false
        tags:
            - { name: twig.extension }

    oro_bugtracker.twig_extension.order:
            class: Oro\BugTrackerBundle\Twig\CollectionOrderExtension
            public: false
            tags:
                - { name: twig.extension }

    oro_bugtracker.twig_extension.activity:
            class: Oro\BugTrackerBundle\Twig\ActivityExtension
            public: false
            tags:
                - { name: twig.extension }

    oro_bugtracker.handler.project:
        class: Oro\BugTrackerBundle\Form\Handler\ProjectHandler
        public: true
        arguments:
            ["@request_stack","@doctrine.orm.entity_manager"]

    oro_bugtracker.handler.issue:
            class: Oro\BugTrackerBundle\Form\Handler\IssueHandler
            public: true
            arguments:
                ["@request_stack","@doctrine.orm.entity_manager","@security.token_storage","@oro_bugtracker.handler.activity"]

    oro_bugtracker.handler.customer:
            class: Oro\BugTrackerBundle\Form\Handler\CustomerHandler
            public: true
            arguments:
                ["@request_stack","@doctrine.orm.entity_manager","@security.password_encoder"]

    oro_bugtracker.handler.comment:
                class: Oro\BugTrackerBundle\Form\Handler\CommentHandler
                public: true
                arguments:
                    ["@request_stack","@doctrine.orm.entity_manager","@oro_bugtracker.handler.activity"]

    oro_bugtracker.handler.activity:
                    class: Oro\BugTrackerBundle\Form\Handler\ActivityHandler
                    public: true
                    arguments:
                        ["@request_stack","@doctrine.orm.entity_manager","@security.token_storage"]
