services:
    #twig extensions
    oro_bugtracker.twig_extension.paginator:
            class: Oro\BugTrackerBundle\Twig\PaginatorExtension
            arguments:
                 ["@request_stack","@doctrine.orm.entity_manager"]
            public: false
            tags:
                - { name: twig.extension }

    oro_bugtracker.twig_extension.order:
            class: Oro\BugTrackerBundle\Twig\CollectionOrderExtension
            public: false
            tags:
                - { name: twig.extension }

    oro_bugtracker.twig_extension.class:
            class: Oro\BugTrackerBundle\Twig\ClassExtension
            public: false
            tags:
                - { name: twig.extension }

    # form handlers
    oro_bugtracker.handler.project:
            class: Oro\BugTrackerBundle\Form\Handler\ProjectHandler
            public: true
            arguments:
                ["@request_stack","@doctrine.orm.entity_manager"]

    oro_bugtracker.handler.issue:
            class: Oro\BugTrackerBundle\Form\Handler\IssueHandler
            public: true
            arguments:
                - "@request_stack"
                - "@doctrine.orm.entity_manager"
                - "@security.token_storage"
                - "@event_dispatcher"

    oro_bugtracker.handler.customer:
            class: Oro\BugTrackerBundle\Form\Handler\CustomerHandler
            public: true
            arguments:
                ["@request_stack","@doctrine.orm.entity_manager","@security.password_encoder"]

    oro_bugtracker.handler.comment:
            class: Oro\BugTrackerBundle\Form\Handler\CommentHandler
            public: true
            arguments:
                - "@request_stack"
                - "@doctrine.orm.entity_manager"
                - "@security.token_storage"
                - "@event_dispatcher"

    #security
    oro_bugtracker.issue_voter:
            class: Oro\BugTrackerBundle\Security\IssueVoter
            arguments:
                    ["@doctrine.orm.entity_manager", "@security.access.decision_manager"]
            public: false
            tags:
                - { name: security.voter }

    oro_bugtracker.comment_voter:
            class: Oro\BugTrackerBundle\Security\CommentVoter
            arguments:
                    ["@doctrine.orm.entity_manager", "@security.access.decision_manager"]
            public: false
            tags:
                - { name: security.voter }

    # event listeners
    oro_bugtracker.event_listener.handle_activity:
            class: Oro\BugTrackerBundle\EventListener\ActivityListener
            arguments:
                - "@doctrine.orm.entity_manager"
                - "@security.token_storage"
            tags:
                - { name: kernel.event_listener, event: oro_bugtracker.comment.before_create, method: addCommentCreateActivity }
                - { name: kernel.event_listener, event: oro_bugtracker.comment.before_update, method: addCommentUpdateActivity }
                - { name: kernel.event_listener, event: oro_bugtracker.comment.before_delete, method: addCommentDeleteActivity }
                - { name: kernel.event_listener, event: oro_bugtracker.issue.before_create,   method: addIssueCreateActivity }
                - { name: kernel.event_listener, event: oro_bugtracker.issue.before_update,   method: addIssueUpdateActivity }


