services:
    app.twig_extension:
        class: Oro\BugTrackerBundle\Twig\PaginatorExtension
        public: false
        tags:
            - { name: twig.extension }

    oro_bugtracker.handler.project:
        class: Oro\BugTrackerBundle\Form\Handler\ProjectHandler
        public: true
        arguments:
            ["@request_stack","@doctrine.orm.entity_manager"]