<?php

namespace Oro\BugTrackerBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Oro\BugTrackerBundle\Entity\Activity;
use Oro\BugTrackerBundle\Entity\Issue;
use Oro\BugTrackerBundle\Entity\Project;
use Oro\BugTrackerBundle\Entity\Customer;
use Doctrine\Common\Collections\Criteria;
use Oro\BugTrackerBundle\Repository\Paginator\PageBuilder;
use Oro\BugTrackerBundle\Repository\Paginator\PaginatorInterface;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository implements PaginatorInterface
{
    use PageBuilder;


    /**
     * @param $method
     * @param array $attributes
     * @return bool
     */
    public function getQbByCustomCondition($method, array $attributes)
    {
        $qb = false;
        switch ($method) {
            case 'project_activities';
                list($project) = $attributes;
                $qb = $this->getActivityProjectCollection(
                    $project
                );
                break;

            case 'customer_activities';
                list($customer) = $attributes;
                $qb = $this->getActivityCustomerCollection(
                    $customer
                );
                break;
        }

        return $qb;
    }

    /**
     * @param Customer $customer
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getActivityCustomerCollection(Customer $customer)
    {
        $activityQb = $this->createQueryBuilder('activity');
        $activityQb->where('activity.customer = :customer');
        $activityQb->setParameter('customer', $customer);
        $activityQb->orderBy('activity.date', Criteria::DESC);

        return $activityQb;
    }

    /**
     * @param Project $project
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getActivityProjectCollection(Project $project)
    {
        $activityQb = $this->createQueryBuilder('activity');
        $activityQb->where('activity.project = :project');
        $activityQb->setParameter('project', $project);
        $activityQb->orderBy('activity.date', Criteria::DESC);

        return $activityQb;
    }

    /**
     * @param Issue $issue
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getActivityIssueCollection(Issue $issue)
    {
        $activityQb = $this->createQueryBuilder('activity');
        $activityQb->where('activity.issue = :issue');
        $activityQb->setParameter('issue', $issue);
        $activityQb->orderBy('activity.date', Criteria::DESC);

        return $activityQb;
    }
}
