<?php

namespace Oro\BugTrackerBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Oro\BugTrackerBundle\Entity\Customer;
use Oro\BugTrackerBundle\Repository\Paginator\QueryPageBuilder;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    use QueryPageBuilder;
    /**
     * @param array $objectCollection
     * @param array $fields
     *
     * @return array
     */
    public function convertCollectionToAssoc($objectCollection, $fields)
    {
        $result = [];
        $inc = 0;
        foreach ($objectCollection as $object) {
            foreach ($fields as $field) {
                $result[$inc][$field] = '';
                if ((is_object($object))) {
                    $getFieldNameFunction = 'get'.ucfirst($field);
                    if (method_exists($object, $getFieldNameFunction)) {
                        $result[$inc][$field] = $object->$getFieldNameFunction();
                    }
                } elseif (is_array($object)) {
                    $result[$inc][$field] = $object[$field];
                }
            }
            $inc++;
        }

        return $result;
    }

    public function getProjectMembersListBySlug($slug)
    {
        $em = $this->getEntityManager();
        $customerRepository = $em->getRepository(Customer::class);
        if ($slug) {
            $conditionCollection = ['username' => ['like' => $slug.'%']];
            $findResult = $customerRepository->findByCondition($conditionCollection);
            $findResult = (is_array($findResult)) ? $findResult : [$findResult];

            $memberListAssoc = $customerRepository->convertCollectionToAssoc($findResult, ['username']);
            return (empty($memberListAssoc)) ? [] : array_column($memberListAssoc, 'username');
        }

        return false;
    }
}
