<?php

namespace Oro\BugTrackerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    /**
     * @param array $objectCollection
     * @param array $fields
     *
     * @return array
     */
    public function convertCollectionToAssoc($objectCollection, $fields)
    {
        $result = [];
        $inc = 0;
        foreach ($objectCollection as $object) {
            foreach ($fields as $field) {
                $result[$inc][$field] = '';
                if ((is_object($object))) {
                    $getFieldNameFunction = 'get'.ucfirst($field);
                    if (method_exists($object, $getFieldNameFunction)) {
                        $result[$inc][$field] = $object->$getFieldNameFunction();
                    }
                } elseif (is_array($object)) {
                    $result[$inc][$field] = $object[$field];
                }
            }
            $inc++;
        }

        return $result;
    }
}
